In [ ]:
!pip install tensorflow==1.14.0

     |████████████████████████████████| 109.2MB 28kB/s 
     |████████████████████████████████| 491kB 37.7MB/s 
     |████████████████████████████████| 3.2MB 37.1MB/s 
  Found existing installation: tensorflow-estimator 2.2.0rc0
    Uninstalling tensorflow-estimator-2.2.0rc0:
      Successfully uninstalled tensorflow-estimator-2.2.0rc0
  Found existing installation: tensorboard 2.1.1
    Uninstalling tensorboard-2.1.1:
      Successfully uninstalled tensorboard-2.1.1
  Found existing installation: tensorflow 2.2.0rc1
    Uninstalling tensorflow-2.2.0rc1:
      Successfully uninstalled tensorflow-2.2.0rc1


In [ ]:
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Convolution2D,GlobalMaxPooling2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten,Dropout
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.applications import imagenet_utils
from tensorflow.keras.optimizers import Adam,SGD
import numpy as np
import pandas as pd
import glob
import os
import csv
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

Mounted at /content/gdrive


STORING EXTRACTED FEATURES IN CSV-TRAIN

In [ ]:
path_train_fire='/content/drive/My Drive/dataset/training_dataset/fire'
files_train_fire = os.listdir(path_train_fire)

train_fire_label=[]
train_fire_path=[]
for dir in files_train_fire:
  train_fire_label.append(dir)
  img_path=os.path.join(path_train_fire,dir)
  train_fire_path.append(img_path)


batch_size=64



count=0
for (b,i) in enumerate(range(0,len(train_fire_path),batch_size)):
  print(count)
  batch_images=[]
  batch_path=train_fire_path[i:i+batch_size]
  batch_label=train_fire_label[i:i+batch_size]
  if(count>=48):
    for img_path in batch_path:
      print(img_path)
      image = load_img(img_path, target_size=(224, 224))
      image = img_to_array(image)
      image = np.expand_dims(image, axis=0)
      image = imagenet_utils.preprocess_input(image)
      batch_images.append(image)
    batch_images=np.vstack(batch_images)
    inc_model = InceptionV3(weights="imagenet",include_top=False)
    features=inc_model.predict(batch_images,batch_size=batch_size)
    features = features.reshape((features.shape[0], 5*5*2048))
    for (label, vec) in zip(batch_label, features):
      vec = ",".join([str(v) for v in list(vec)])
      with open(r'/content/drive/My Drive/updated_train.csv', 'a') as f:
        f.write("{},{},{}\n".format(label, vec,'1'))
  count+=1






0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1516.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1522.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1519.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1518.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1517.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1520.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_152.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1524.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1528.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1533.jpg
/content/drive/My Drive/dataset/training_dataset/fire/fire_train_1526.jpg
/content/drive/My Drive/dataset/training_dataset/f

In [ ]:


path_train_nofire='/content/drive/My Drive/dataset/training_dataset/nofire'
files_train_nofire = os.listdir(path_train_nofire)

train_nofire_label=[]
train_nofire_path=[]
for dir in files_train_nofire:
  train_nofire_label.append(dir)
  img_path=os.path.join(path_train_nofire,dir)
  train_nofire_path.append(img_path)


batch_size=64



count=0
for (b,i) in enumerate(range(0,len(train_nofire_path),batch_size)):
  print(count)
  batch_images=[]
  batch_path=train_nofire_path[i:i+batch_size]
  batch_label=train_nofire_label[i:i+batch_size]
  if(count>=7):
    for img_path in batch_path:
      print(img_path)
      image = load_img(img_path, target_size=(224, 224))
      image = img_to_array(image)
      image = np.expand_dims(image, axis=0)
      image = imagenet_utils.preprocess_input(image)
      batch_images.append(image)
    batch_images=np.vstack(batch_images)
    inc_model = InceptionV3(weights="imagenet",include_top=False)
    features=inc_model.predict(batch_images,batch_size=batch_size)
    features = features.reshape((features.shape[0], 5 * 5 * 2048))
    for (label, vec) in zip(batch_label, features):
      vec = ",".join([str(v) for v in list(vec)])
      with open(r'/content/drive/My Drive/updated_train.csv', 'a') as f:
        f.write("{},{},{}\n".format(label, vec,'0'))
  count+=1

0
1
2
3
4
5
6
7
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_989.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_99.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_990.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_999.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_993.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_994.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_995.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_996.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_997.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_991.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_992.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_998.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofir

/usr/local/lib/python3.6/dist-packages/PIL/Image.py:932: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1944.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1945.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1946.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1952.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1948.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1951.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1947.jpg
87916544/87910968 [==============================] - 1s 0us/step
8
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_195.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1950.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1949.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1953.jpg
/content/drive/My Drive/dataset/training_dataset/nofire/nofire_train_1954.jp

In [ ]:
from matplotlib import pyplot
from numpy import expand_dims
# load the model
model = InceptionV3()
# redefine model to output right after the first hidden layer
model = Model(inputs=model.inputs, outputs=model.layers[1].output)
model.summary()
# load the image with the required shape
img = load_img('/content/drive/My Drive/fire_train_2755.jpg', target_size=(224, 224))
# convert the image to an array
img = img_to_array(img)
# expand dimensions so that it represents a single 'sample'
img = expand_dims(img, axis=0)
# prepare the image (e.g. scale pixel values for the vgg)
img = preprocess_input(img)
# get feature map for first hidden layer
feature_maps = model.predict(img)
# plot all 64 maps in an 8x8 squares
square = 8
ix = 1
for _ in range(square):
	for _ in range(square):
		# specify subplot and turn of axis
		ax = pyplot.subplot(square, square, ix)
		ax.set_xticks([])
		ax.set_yticks([])
		# plot filter channel in grayscale
		pyplot.imshow(feature_maps[0, :, :, ix-1], cmap='gray')
		ix += 1
# show the figure
pyplot.show()

41951232/96112376 [============>.................] - ETA: 1s

STORING EXTRACTED FEATURES IN CSV-VALIDATION

In [ ]:
path_test_fire='/content/drive/My Drive/dataset/test_dataset/fire'
files_test_fire = os.listdir(path_test_fire)

test_fire_label=[]
test_fire_path=[]
for dir in files_test_fire:
  test_fire_label.append(dir)
  img_path=os.path.join(path_test_fire,dir)
  test_fire_path.append(img_path)


batch_size=64



count=0
for (b,i) in enumerate(range(0,len(test_fire_path),batch_size)):
  print(count)
  batch_images=[]
  batch_path=test_fire_path[i:i+batch_size]
  batch_label=test_fire_label[i:i+batch_size]
  if(count>=0):
    for img_path in batch_path:
      print(img_path)
      image = load_img(img_path, target_size=(224, 224))
      image = img_to_array(image)
      image = np.expand_dims(image, axis=0)
      image = imagenet_utils.preprocess_input(image)
      batch_images.append(image)
    batch_images=np.vstack(batch_images)
    inc_model = InceptionV3(weights="imagenet",include_top=False)
    features=inc_model.predict(batch_images,batch_size=batch_size)
    features = features.reshape((features.shape[0], 5* 5 * 2048))
    for (label, vec) in zip(batch_label, features):
      vec = ",".join([str(v) for v in list(vec)])
      with open('/content/drive/My Drive/validation.csv', 'a') as f:
        f.write("{},{},{}\n".format(label, vec,'1'))
  count+=1

0
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_328.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_336.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_333.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_33.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_332.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_329.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_330.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_331.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_335.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_334.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_337.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_339.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_342.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_345.jpg
/content/drive/My Drive/dataset/test_dataset/fi

/usr/local/lib/python3.6/dist-packages/PIL/Image.py:932: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


/content/drive/My Drive/dataset/test_dataset/fire/fire_test_87.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_83.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_89.jpg
7
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_82.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_9.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_90.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_92.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_91.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_97.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_96.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_94.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_93.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_95.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_99.jpg
/content/drive/My Drive/dataset/test_dataset/fire/fire_test_9

In [ ]:
path_test_nofire='/content/drive/My Drive/dataset/test_dataset/nofire'
files_test_nofire = os.listdir(path_test_nofire)

test_nofire_label=[]
test_nofire_path=[]
for dir in files_test_nofire:
  test_nofire_label.append(dir)
  img_path=os.path.join(path_test_nofire,dir)
  test_nofire_path.append(img_path)


batch_size=64



count=0
for (b,i) in enumerate(range(0,len(test_nofire_path),batch_size)):
  print(count)
  batch_images=[]
  batch_path=test_nofire_path[i:i+batch_size]
  batch_label=test_nofire_label[i:i+batch_size]
  if(count>=0):
    for img_path in batch_path:
      print(img_path)
      image = load_img(img_path, target_size=(224, 224))
      image = img_to_array(image)
      image = np.expand_dims(image, axis=0)
      image = imagenet_utils.preprocess_input(image)
      batch_images.append(image)
    batch_images=np.vstack(batch_images)
    inc_model = InceptionV3(weights="imagenet",include_top=False)
    features=inc_model.predict(batch_images,batch_size=batch_size)
    features = features.reshape((features.shape[0], 5 * 5 * 2048))
    for (label, vec) in zip(batch_label, features):
      vec = ",".join([str(v) for v in list(vec)])
      with open(r'/content/drive/My Drive/validation.csv', 'a') as f:
        f.write("{},{},{}\n".format(label, vec,'0'))
  count+=1

0
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_131.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_145.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_146.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_221.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_242.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_268.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_282.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_77.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_10.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_101.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_102.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_0.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_1.jpg
/content/drive/My Drive/dataset/test_dataset/nofire/nofire_test_103.

EXTRACTING X FROM CSV

In [ ]:
chunksize = 1
for chunk in pd.read_csv('/content/drive/My Drive/updated_train.csv', chunksize=chunksize):
    X=chunk.iloc[:,:].values
    break

chunksize=64
count=0
for chunk in pd.read_csv('/content/drive/My Drive/updated_train.csv', chunksize=chunksize):

  if(count<25 or count>60):

      k=chunk.iloc[:,:].values
      X=np.append(X,k,axis=0)

  print(count)
  count+=1
  print(X.shape)





0
(65, 51202)
1
(129, 51202)
2
(193, 51202)
3
(257, 51202)
4
(321, 51202)
5
(385, 51202)
6
(449, 51202)
7
(513, 51202)
8
(577, 51202)
9
(641, 51202)
10
(705, 51202)
11
(769, 51202)
12
(833, 51202)
13
(897, 51202)
14
(961, 51202)
15
(1025, 51202)
16
(1089, 51202)
17
(1153, 51202)
18
(1217, 51202)
19
(1281, 51202)
20
(1345, 51202)
21
(1409, 51202)
22
(1473, 51202)
23
(1537, 51202)
24
(1601, 51202)
25
(1601, 51202)
26
(1601, 51202)
27
(1601, 51202)
28
(1601, 51202)
29
(1601, 51202)
30
(1601, 51202)
31
(1601, 51202)
32
(1601, 51202)
33
(1601, 51202)
34
(1601, 51202)
35
(1601, 51202)
36
(1601, 51202)
37
(1601, 51202)
38
(1601, 51202)
39
(1601, 51202)
40
(1601, 51202)
41
(1601, 51202)
42
(1601, 51202)
43
(1601, 51202)
44
(1601, 51202)
46
(1601, 51202)
47
(1601, 51202)
48
(1601, 51202)
49
(1601, 51202)
50
(1601, 51202)
51
(1601, 51202)
52
(1601, 51202)
53
(1601, 51202)
54
(1601, 51202)
55
(1601, 51202)
56
(1601, 51202)
57
(1601, 51202)
58
(1601, 51202)
59
(1601, 51202)
60
(1601, 51202)
61
(16

In [ ]:
y=X[1:,-1]
X=X[1:,1:-1]


In [ ]:
print(X.shape,y.shape)

(3735, 51200) (3735,)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 57)



In [ ]:
import pickle
with open('/content/drive/My Drive/train_final.pkl','wb') as f:
  pickle.dump((X,y),f)

In [ ]:
print(X_train)

[[25.614489000000003 5.587248000000001 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.5454755 ... 0.0 0.0 0.0]
 [21.416677 0.0 0.0 ... 5.1803254999999995 0.0 0.0]
 ...
 [4.9607887 0.0 5.41441 ... 0.0 0.0 0.0]
 [0.0 0.0 19.634678 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]]


In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X=sc.transform(X)

In [ ]:
y_train=y_train.astype(int)
y_test=y_test.astype(int)


In [ ]:
def print_conf(y_test,y_pred,method):
  cm = confusion_matrix(y_test, y_pred)
  print(method)
  print(cm)
  print ('Accuracy Score :',accuracy_score(y_test, y_pred))



In [ ]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print_conf(y_test,y_pred,'logistic regression')

logistic regression
[[474  62]
 [ 82 316]]
Accuracy Score : 0.8458244111349036


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print_conf(y_test,y_pred,'knn-5')

knn-5
[[450  86]
 [169 229]]
Accuracy Score : 0.7269807280513919


In [ ]:
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print_conf(y_test,y_pred,'knn-3')

knn-3
[[440  96]
 [158 240]]
Accuracy Score : 0.728051391862955


In [ ]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print_conf(y_test,y_pred,'SVM')

SVM
[[482  54]
 [114 284]]
Accuracy Score : 0.8201284796573876


In [ ]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print_conf(y_test,y_pred,'Naive Bayes')

Naive Bayes
[[472  64]
 [159 239]]
Accuracy Score : 0.7612419700214133


In [ ]:
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 50)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print_conf(y_test,y_pred,'DecisionTree')

DecisionTree
[[433 103]
 [135 263]]
Accuracy Score : 0.7451820128479657


In [ ]:
classifier = RandomForestClassifier(n_estimators = 128, criterion = 'gini', random_state = 50)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print_conf(y_test,y_pred,'RandomForest')

RandomForest
[[480  56]
 [108 290]]
Accuracy Score : 0.8244111349036403


FORMING X_VAL AND Y_VAL

In [ ]:
import pandas as pd
chunksize = 1
for chunk in pd.read_csv('/content/drive/My Drive/validation.csv', chunksize=chunksize):
    X_val=chunk.iloc[:,:].values

    break
chunksize=64

count=0
for chunk in pd.read_csv('/content/drive/My Drive/validation.csv', chunksize=chunksize):

  if(count>=0):

      k=chunk.iloc[:,:].values
      X_val=np.append(X_val,k,axis=0)

  print(count)
  count+=1
  print(X_val.shape)


0
(65, 51202)
1
(129, 51202)
2
(193, 51202)
3
(257, 51202)
4
(321, 51202)
5
(385, 51202)
6
(449, 51202)
7
(513, 51202)
8
(577, 51202)
9
(641, 51202)
10
(705, 51202)
11
(769, 51202)
12
(833, 51202)
13
(897, 51202)
14
(961, 51202)
15
(1025, 51202)
16
(1070, 51202)


In [ ]:
y_val=X_val[1:,-1]
X_val=X_val[1:,1:-1]


In [ ]:
X_val=sc.fit_transform(X_val)

In [ ]:
y=y.astype(int)
y_val=y_val.astype(int)

In [ ]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_val)
print_conf(y_val,y_pred,'logistic regression')

logistic regression
[[340  13]
 [132 584]]
Accuracy Score : 0.8643592142188962


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_val)
print_conf(y_val,y_pred,'knn-5')

knn-5
[[306  47]
 [244 472]]
Accuracy Score : 0.7277829747427502


In [ ]:
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_val)
print_conf(y_val,y_pred,'knn-3')

knn-3
[[297  56]
 [221 495]]
Accuracy Score : 0.7408793264733395


In [ ]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_val)
print_conf(y_val,y_pred,'SVM')

SVM
[[330  23]
 [206 510]]
Accuracy Score : 0.7857811038353602


In [ ]:
classifier = GaussianNB()
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_val)
print_conf(y_val,y_pred,'Naive Bayes')

Naive Bayes
[[330  23]
 [348 368]]
Accuracy Score : 0.6529466791393826


In [ ]:
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 50)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_val)
print_conf(y_val,y_pred,'DecisionTree')

DecisionTree
[[271  82]
 [206 510]]
Accuracy Score : 0.7305893358278766


In [ ]:
classifier = RandomForestClassifier(n_estimators = 128, criterion = 'gini', random_state = 50)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_val)
print_conf(y_val,y_pred,'RandomForest')

RandomForest
[[321  32]
 [160 556]]
Accuracy Score : 0.8203928905519177
